spring.application.name=myapp
server.port=8585
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.exclude=info,health
management.info.env.enabled=true
info.app.name=My Super cool App
info.app.descripton=A very awesome app
info.app.version=1.0.0